### ISSUE TITLE
CIPs & Site Improvements tracking EPIC

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/CIPs#183]
```[tasklist]
### Tasks
- [x] Link to the GitHub page for each CIP inside the page for each CIP on the site. This is kind of done with the 📝 "suggest an edit" button on top right of each page, but it is not ideal for viewing.
- [ ] https://github.com/celestiaorg/CIPs/issues/186
- [x] Change page names of README.md's on working groups directory so that they can be linked with `page.md` instead of `index.html`, so that it works on github too
- [ ] define WGs somewhere in CIP repo in issue #237
- [ ] https://github.com/celestiaorg/CIPs/issues/189
- [ ] https://github.com/celestiaorg/CIPs/issues/200
```
